[package]
name = "fast-steal"
description = "特别快的多线程库，支持超细颗粒度的任务窃取"
version = "0.1.0"
edition = "2024"
authors = ["share121 <2854631158@qq.com>"]
license = "MIT"

[dependencies]
crossbeam-channel = "0.5.14"
